### ISSUE TITLE
Store Front - Bookings 

### ISSUE THREAD

**Issue by aknakshay** [shubh28/safeslot#19]
Bookings should be shown date wise and past bookings should go in history tab.

**Comment by 3sanket3** [comment]
Done https://github.com/shubh28/safeslot-client/pull/10

**Comment by aknakshay** [comment]
We should have cascading slots here wherein names of people who booked stores should come.

**Comment by 3sanket3** [comment]
@aknakshay Is there anything pending on the same? Please close this if not.
