### ISSUE TITLE
Remove fields from store referral registrations

### ISSUE THREAD

**Issue by aknakshay** [shubh28/safeslot#46]
https://safeslot.in/refer
Remove GSTIN number, and store size from referral registrations.

**Comment by christenmartin** [comment]
So just remove them from the form, but keep GSTIN and store size on the store model?

**Comment by aknakshay** [comment]
Yes, Correct. We want it to be in the model but not on the referral form since users who are referring it won't have this information. It's just making the form longer.

**Comment by christenmartin** [comment]
Deployed changes on surge http://learned-copper.surge.sh/
