### ISSUE TITLE
Way to go to the Bookings page

### ISSUE THREAD

**Issue by aknakshay** [shubh28/safeslot#55]
Once a user is logged in, he needs to book a new slot to go to the bookings page or need to enter the URL safeslot.in/bookings to go there.

On nearby stores page, instead of logout, we should have a 'Bookings'/'Account' page option. As logout button is also present on the bookings page, we do not need to insert that on nearby stores page.

**Comment by APTricou** [comment]
Hamburger Menu pushed. Should allow access to any other page from any page with a header.
